# --- Stock Lists ---
STOCK_UNIVERSE = {
    "Nifty 50 Stocks": [
        "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK",
        "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BEL", "BPCL",
        "BHARTIARTL", "BRITANNIA", "CIPLA", "COALINDIA", "DRREDDY",
        "EICHERMOT", "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE",
        "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK", "ITC",
        "INDUSINDBK", "INFY", "JSWSTEEL", "KOTAKBANK", "LT",
        "M&M", "MARUTI", "NTPC", "NESTLEIND", "ONGC",
        "POWERGRID", "RELIANCE", "SBILIFE", "SHRIRAMFIN", "SBIN",
        "SUNPHARMA", "TCS", "TATACONSUM", "TATAMOTORS", "TATASTEEL",
        "TECHM", "TITAN", "TRENT", "ULTRACEMCO", "WIPRO"
    ],
    "Nifty Midcap 50 Stocks": [
        "ACC", "APLAPOLLO", "AUBANK", "ABCAPITAL", "ALKEM",
        "ASHOKLEY", "ASTRAL", "AUROPHARMA", "BHARATFORG", "CGPOWER",
        "COLPAL", "CONCOR", "CUMMINSIND", "DIXON", "FEDERALBNK",
        "GMRAIRPORT", "GODREJPROP", "HDFCAMC", "HINDPETRO", "IDFCFIRSTB",
        "INDHOTEL", "INDUSTOWER", "KPITTECH", "LTF", "LUPIN", "MRF",
        "MARICO", "MAXHEALTH", "MPHASIS", "MUTHOOTFIN", "NMDC",
        "OBEROIRLTY", "OFSS", "POLICYBZR", "PIIND", "PERSISTENT",
        "PETRONET", "PHOENIXLTD", "POLYCAB", "SBICARD", "SRF", "SAIL",
        "SUNDARMFIN", "SUPREMEIND", "SUZLON", "TATACOMM", "UPL", "IDEA",
        "VOLTAS", "YESBANK"
    ],

    "Nifty Smallcap 50 Stocks": [
        "360ONE", "AARTIIND", "ABREL", "ARE&M", "ANGELONE", "APARINDS", "ATUL",
        "BSOFT", "BLUESTARCO", "BRIGADE", "CESC", "CASTROLIND", "CDSL", "CAMS",
        "CROMPTON", "CYIENT", "FINCABLES", "GLENMARK", "GESHIP", "GSPL", "HFCL",
        "HINDCOPPER", "IIFL", "INDIAMART", "IEX", "KPIL", "KARURVYSYA", "LAURUSLABS",
        "MGL", "MANAPPURAM", "MCX", "NATCOPHARM", "NBCC", "NCC", "NH", "NATIONALUM",
        "NAVINFLUOR", "PNBHOUSING", "PVRINOX", "PEL", "PPLPHARMA", "RBLBANK", "RADICO",
        "RKFORGE", "REDINGTON", "SONATSOFTW", "TEJASNET", "RAMCOCEM", "ZEEL", "ZENSARTECH"
    ],
    "Nifty Auto Stocks": [
        "APOLLOTYRE", "ASHOKLEY", "BAJAJ-AUTO", "BALKRISIND", "BHARATFORG",
        "BOSCHLTD", "EICHERMOT", "EXIDEIND", "HEROMOTOCO", "MRF",
        "M&M", "MARUTI", "MOTHERSON", "TVSMOTOR", "TATAMOTORS"
    ],
    "Nifty Bank Stocks": [
        "AUBANK", "AXISBANK", "BANKBARODA", "CANBK", "FEDERALBNK",
        "HDFCBANK", "ICICIBANK", "IDFCFIRSTB", "INDUSINDBK", "KOTAKBANK",
        "PNB", "SBIN"
    ],
    "Nifty Chemicals": [
    "AARTIIND", "ATUL", "BAYERCROP", "CHAMBLFERT", "COROMANDEL", "DEEPAKNTR", "EIDPARRY",
    "FLUOROCHEM", "GNFC", "HSCL", "LINDEINDIA", "NAVINFLUOR", "PCBL", "PIIND", "PIDILITIND",
    "SRF", "SOLARINDS", "SUMICHEM", "TATACHEM", "UPL"
    ],
    "Nifty Financial Services":[
        "AXISBANK", "BAJFINANCE", "BAJAJFINSV", "CHOLAFIN", "HDFCAMC", "HDFCBANK",
        "HDFCLIFE", "ICICIBANK", "ICICIGI", "ICICIPRULI", "KOTAKBANK", "LICHSGFIN",
        "MCX", "MUTHOOTFIN", "PFC", "RECLTD", "SBICARD", "SBILIFE", "SHRIRAMFIN", "SBIN"
    ],
    "Nifty FMCG":[
        "BALRAMCHIN", "BRITANNIA", "COLPAL", "DABUR", "GODREJCP", "HINDUNILVR",
        "ITC", "MARICO", "NESTLEIND", "PGHH", "RADICO", "TATACONSUM",
        "UBL", "UNITDSPR", "VBL"
    ],
    "Nifty Healthcare":[
        "ABBOTINDIA", "ALKEM", "APOLLOHOSP", "AUROPHARMA", "BIOCON", "CIPLA",
        "DIVISLAB", "LALPATHLAB", "DRREDDY", "GLENMARK", "GRANULES", "IPCALAB",
        "LAURUSLABS", "LUPIN", "MAXHEALTH", "METROPOLIS", "SUNPHARMA", "SYNGENE",
        "TORNTPHARM", "ZYDUSLIFE"
    ],
    "Nifty IT":[
        "COFORGE", "HCLTECH", "INFY", "LTTS", "LTIM", "MPHASIS",
        "PERSISTENT", "TCS", "TECHM", "WIPRO"
    ],
    "Nifty Media":[
        "DEN", "DISHTV", "HATHWAY", "NAZARA", "NETWORK18", "PVRINOX",
        "SAREGAMA", "SUNTV", "TIPSMUSIC", "ZEEL"
    ],
    "Nifty Metal":[
        "APLAPOLLO", "ADANIENT", "HINDALCO", "HINDCOPPER", "HINDZINC", "JSWSTEEL",
        "JSL", "JINDALSTEL", "NMDC", "NATIONALUM", "RATNAMANI", "SAIL",
        "TATASTEEL", "VEDL", "WELCORP"
    ],
    "Nifty Pharma":[
        "ABBOTINDIA", "AJANTPHARM", "ALKEM", "AUROPHARMA", "BIOCON", "CIPLA",
        "DIVISLAB", "DRREDDY", "GLAND", "GLENMARK", "GRANULES", "IPCALAB",
        "JBCHEPHARM", "LAURUSLABS", "LUPIN", "MANKIND", "NATCOPHARM", "SUNPHARMA",
        "TORNTPHARM", "ZYDUSLIFE"
    ],
    "Nifty Private Bank":[
        "AXISBANK", "BANDHANBNK", "CUB", "FEDERALBNK", "HDFCBANK", "ICICIBANK",
        "IDFCFIRSTB", "INDUSINDBK", "KOTAKBANK", "RBLBANK"
    ],
    "Nifty PSU Bank":[
        "BANKBARODA", "BANKINDIA", "MAHABANK", "CANBK", "CENTRALBK", "INDIANB",
        "IOB", "PSB", "PNB", "SBIN", "UCOBANK", "UNIONBANK"
    ],
    "Nifty Realty":[
        "BRIGADE", "DLF", "GODREJPROP", "LODHA", "MAHLIFE", "OBEROIRLTY",
        "PHOENIXLTD", "PRESTIGE", "RAYMOND", "SOBHA"
    ],
    "Nifty Consumer Durables":[
        "AMBER", "BATAINDIA", "BLUESTARCO", "CENTURYPLY", "CERA", "CROMPTON",
        "DIXON", "HAVELLS", "KAJARIACER", "KALYANKJIL", "RAJESHEXPO", "TITAN",
        "VGUARD", "VOLTAS", "WHIRLPOOL"
    ],
    "Nifty Oil & Gas":[
        "ATGL", "AEGISLOG", "BPCL", "CASTROLIND", "GAIL", "GUJGASLTD",
        "GSPL", "HINDPETRO", "IOC", "IGL", "MGL", "ONGC", "OIL",
        "PETRONET", "RELIANCE"
    ],
    "Nifty Commodities":[
        "ACC", "APLAPOLLO", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM",
        "BPCL", "COALINDIA", "GRASIM", "HINDALCO", "HINDPETRO", "IOC",
        "JSWENERGY", "JSWSTEEL", "JINDALSTEL", "NHPC", "NMDC", "NTPC",
        "ONGC", "PIIND", "PIDILITIND", "RELIANCE", "SRF", "SHREECEM",
        "SAIL", "TATAPOWER", "TATASTEEL", "UPL", "ULTRACEMCO", "VEDL"
    ],
    "Nifty Core Housing":[
        "ACC", "AAVAS", "AMBUJACEM", "ASIANPAINT", "BERGEPAINT", "BLUESTARCO",
        "CROMPTON", "DLF", "DALBHARAT", "DIXON", "GODREJPROP", "GRASIM",
        "HAVELLS", "HDFC", "IBULHSGFIN", "JKCEMENT", "KEI", "KAJARIACER",
        "KANSAINER", "LICHSGFIN", "LODHA", "OBEROIRLTY", "PHOENIXLTD", "POLYCAB",
        "PRESTIGE", "SHREECEM", "RAMCOCEM", "ULTRACEMCO", "VOLTAS", "WHIRLPOOL"
    ],
    "Nifty Energy":[
        "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "ATGL", "AEGISLOG",
        "BHEL", "BPCL", "CESC", "CGPOWER", "CASTROLIND", "COALINDIA", "GAIL",
        "GVT&D", "GUJGASLTD", "GSPL", "HINDPETRO", "POWERINDIA", "IOC", "IGL",
        "INOXWIND", "JSWENERGY", "JPPOWER", "MGL", "NHPC", "NLCINDIA", "NTPC",
        "ONGC", "OIL", "PETRONET", "POWERGRID", "RELIANCE", "SJVN", "SCHNEIDER",
        "SIEMENS", "SUZLON", "TATAPOWER", "THERMAX", "TORNTPOWER", "TRITURBINE"
    ],
    "Nifty EV & New Age Automotive":[
        "ARE&M", "ASHOKLEY", "BAJAJ-AUTO", "BHARATFORG", "BOSCHLTD", "CGPOWER",
        "EICHERMOT", "EXIDEIND", "FLUOROCHEM", "HEROMOTOCO", "HSCL", "JBMA",
        "JWL", "KPITTECH", "LTTS", "M&M", "MARUTI", "MINDACORP", "MSUMI",
        "OLECTRA", "RTNINDIA", "RELIANCE", "MOTHERSON", "SCHAEFFLER", "SONACOMS",
        "TVSMOTOR", "TATACHEM", "TATAELXSI", "TATAMOTORS", "TATATECH", "TIINDIA",
        "UNOMINDA", "VARROC"
    ],
    "Nifty India Consumption":[
        "ADANIPOWER", "APOLLOHOSP", "ASIANPAINT", "DMART", "BAJAJ-AUTO", "BHARTIARTL",
        "BRITANNIA", "COLPAL", "DLF", "EICHERMOT", "GODREJCP", "HAVELLS",
        "HEROMOTOCO", "HINDUNILVR", "ITC", "INDHOTEL", "NAUKRI", "INDIGO",
        "M&M", "MARUTI", "MAXHEALTH", "NESTLEIND", "TVSMOTOR", "TATACONSUM",
        "TATAPOWER", "TITAN", "TRENT", "UNITDSPR", "VBL", "ZOMATO"
    ],
    "Nifty India Defence":[
        "ASTRAMICRO", "BDL", "BEL", "COCHINSHIP", "DCXINDIA", "DATAPATTNS",
        "DYNAMATECH", "GRSE", "HAL", "IDEAFORGE", "MTARTECH", "MAZDOCK",
        "MIDHANI", "PARAS", "SOLARINDS", "ZENTEC"
    ],
    "Nifty India Digital":[
        "AFFLE", "BHARTIARTL", "BSOFT", "COFORGE", "CYIENT", "NYKAA",
        "HCLTECH", "INDIAMART", "IRCTC", "NAUKRI", "INFY", "INTELLECT",
        "KPITTECH", "LTTS", "LTIM", "MPHASIS", "PAYTM", "OFSS", "POLICYBZR",
        "PERSISTENT", "SONATSOFTW", "TANLA", "TATACOMM", "TCS", "TATAELXSI",
        "TATATECH", "TECHM", "IDEA", "WIPRO", "ZOMATO"
    ],
    "Nifty India Internet & E-Commerce":[
        "ANGELONE", "FIRSTCRY", "CARTRADE", "EASEMYTRIP", "NYKAA", "IIFLCAPS",
        "INDIAMART", "IRCTC", "INFIBEAM", "NAUKRI", "JUSTDIAL", "IXIGO",
        "MOTILALOFS", "NAZARA", "PAYTM", "POLICYBZR", "RTNINDIA", "SWIGGY",
        "TBOTEK", "THOMASCOOK", "ZOMATO"
    ],
    "Nifty India Manufacturing":[
        "ABB", "AIAENG", "APLAPOLLO", "ABREL", "ASHOKLEY", "ASTRAL", "AUROPHARMA",
        "BAJAJ-AUTO", "BALKRISIND", "BEL", "BHARATFORG", "BHEL", "BPCL", "BOSCHLTD",
        "CGPOWER", "CARBORUNIV", "CASTROLIND", "CIPLA", "COCHINSHIP", "COROMANDEL",
        "CROMPTON", "CUMMINSIND", "DEEPAKNTR", "DIVISLAB", "DIXON", "DRREDDY",
        "EICHERMOT", "ESCORTS", "EXIDEIND", "FLUOROCHEM", "HAVELLS", "HEROMOTOCO",
        "HINDALCO", "HAL", "HINDCOPPER", "HINDZINC", "HONAUT", "IOC", "JSWSTEEL",
        "JINDALSTEL", "KPRMILL", "KEI", "LINDEINDIA", "LLOYDSME", "LUPIN", "MRF",
        "M&M", "MARUTI", "MAZDOCK", "METROBRAND", "PIIND", "PAGEIND", "PIDILITIND",
        "POLYCAB", "RELIANCE", "SKFINDIA", "SRF", "MOTHERSON", "SCHAEFFLER", "SIEMENS",
        "SOLARINDS", "SONACOMS", "SUNPHARMA", "SUPREMEIND", "SUZLON", "TVSMOTOR",
        "TATACHEM", "TATAMOTORS", "TATASTEEL", "TEJASNET", "TIMKEN", "TORNTPHARM",
        "TIINDIA", "UPL", "VEDL", "VOLTAS", "ZYDUSLIFE"
    ],
    "Nifty India New Age Consumption":[
        "360ONE", "ABFRL", "AMBER", "ANANTRAJ", "ANGELONE", "DMART", "BLS",
        "BAJAJ-AUTO", "BATAINDIA", "BHARTIARTL", "BLUESTARCO", "BRIGADE", "CELLO",
        "CHALET", "CROMPTON", "DLF", "DEVYANI", "DIXON", "EIHOTEL", "EICHERMOT",
        "NYKAA", "GODREJPROP", "HDFCAMC", "HAVELLS", "HEROMOTOCO", "ISEC",
        "INDIAMART", "INDHOTEL", "IRCTC", "NAUKRI", "INDIGO", "JUBLFOOD",
        "KPRMILL", "KALYANKJIL", "LEMONTREE", "LODHA", "M&M", "MAHLIFE", "MARUTI",
        "METROBRAND", "MOTILALOFS", "NAM-INDIA", "OBEROIRLTY", "OLECTRA", "PAYTM",
        "POLICYBZR", "PVRINOX", "PAGEIND", "PHOENIXLTD", "PRESTIGE", "RAJESHEXPO",
        "RAYMOND", "SAPPHIRE", "SAREGAMA", "SOBHA", "SUNTV", "TVSMOTOR",
        "TATACOMM", "TATAMOTORS", "TTML", "TITAN", "TRENT", "TRIDENT", "UTIAMC",
        "VGUARD", "VIPIND", "VTL", "MANYAVAR", "IDEA", "VOLTAS", "WELSPUNLIV",
        "WESTLIFE", "WHIRLPOOL", "ZEEL", "ZOMATO"
    ],
    "Nifty India Railways PSU":[
        "BEML", "BEL", "BHEL", "CONCOR", "HINDPETRO", "IRCON", "IRCTC",
        "IRFC", "NTPC", "ONGC", "RITES", "RVNL", "RAILTEL", "SAIL"
    ],
    "Nifty India Tourism":[
        "BLS", "CHALET", "DEVYANI", "EIHOTEL", "EASEMYTRIP", "GMRINFRA",
        "INDHOTEL", "IRCTC", "INDIGO", "JUBLFOOD", "LEMONTREE", "MHRIL",
        "RBA", "SAFARI", "SAPPHIRE", "VIPIND", "WESTLIFE"
    ],
    "Nifty MNC":[
        "3MINDIA", "ABB", "ABBOTINDIA", "AMBUJACEM", "ASHOKLEY", "BATAINDIA",
        "BOSCHLTD", "BRITANNIA", "CRISIL", "CASTROLIND", "COLPAL", "CUMMINSIND",
        "ESCORTS", "GLAND", "GRINDWELL", "HINDUNILVR", "HONAUT", "JBCHEPHARM",
        "LINDEINDIA", "MARUTI", "NESTLEIND", "OFSS", "PGHH", "SKFINDIA",
        "SCHAEFFLER", "SIEMENS", "TIMKEN", "UBL", "UNITDSPR", "VEDL"
    ],
    "Nifty PSE":[
        "BEL", "BHEL", "BPCL", "COALINDIA", "CONCOR", "GAIL", "HAL",
        "HINDPETRO", "IOC", "IRCTC", "IRFC", "NHPC", "NMDC", "NTPC",
        "ONGC", "OIL", "PFC", "POWERGRID", "RECLTD", "SAIL"
    ],
    "Nifty Rural":[
        "ACC", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "ASHOKLEY", "ASIANPAINT",
        "ASTRAL", "BAJAJ-AUTO", "BAJFINANCE", "BANDHANBNK", "BANKBARODA", "BANKINDIA",
        "BERGEPAINT", "BHARTIARTL", "BLUESTARCO", "BRITANNIA", "CHOLAFIN", "COLPAL",
        "COROMANDEL", "CROMPTON", "CUMMINSIND", "DABUR", "DALBHARAT", "DIXON",
        "EICHERMOT", "ELGIEQUIP", "EMAMILTD", "ESCORTS", "GODREJCP", "GRASIM",
        "HDFCLIFE", "HAVELLS", "HEROMOTOCO", "HINDUNILVR", "ICICIPRULI", "ITC",
        "INDIANB", "IRCTC", "JKCEMENT", "JSWENERGY", "JIOFIN", "LICHSGFIN",
        "LICI", "M&MFIN", "M&M", "MARICO", "MARUTI", "MFSL", "MUTHOOTFIN",
        "NHPC", "NTPC", "NESTLEIND", "PIIND", "PATANJALI", "POONAWALLA", "PGHH",
        "PNB", "SBICARD", "SBILIFE", "SHREECEM", "SHRIRAMFIN", "SBIN", "SUNDARMFIN",
        "SUPREMEIND", "TVSMOTOR", "TATACOMM", "TATACONSUM", "TATAMOTORS", "TATAPOWER",
        "TORNTPOWER", "UPL", "ULTRACEMCO", "IDEA", "VOLTAS", "ZEEL"
    ],
    "Nifty Non-Cyclical Consumer":[
        "ASIANPAINT", "DMART", "BHARTIARTL", "BRITANNIA", "COLPAL", "CROMPTON",
        "DABUR", "DIXON", "NYKAA", "GODREJCP", "HAVELLS", "HINDUNILVR", "ITC",
        "INDHOTEL", "IRCTC", "NAUKRI", "INDIGO", "JUBLFOOD", "MARICO", "NESTLEIND",
        "PAGEIND", "TATACOMM", "TATACONSUM", "TITAN", "TRENT", "UNITDSPR", "VBL",
        "VOLTAS", "ZEEL", "ZOMATO"
    ]

}
