# --- Stock Lists ---
STOCK_UNIVERSE = {
    "Nifty 50 Stocks": [
        "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
        "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BEL.NS", "BPCL.NS",
        "BHARTIARTL.NS", "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DRREDDY.NS",
        "EICHERMOT.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
        "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS", "ITC.NS",
        "INDUSINDBK.NS", "INFY.NS", "JSWSTEEL.NS", "KOTAKBANK.NS", "LT.NS",
        "M&M.NS", "MARUTI.NS", "NTPC.NS", "NESTLEIND.NS", "ONGC.NS",
        "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SHRIRAMFIN.NS", "SBIN.NS",
        "SUNPHARMA.NS", "TCS.NS", "TATACONSUM.NS", "TATAMOTORS.NS", "TATASTEEL.NS",
        "TECHM.NS", "TITAN.NS", "TRENT.NS", "ULTRACEMCO.NS", "WIPRO.NS"
    ],
    "Nifty Midcap 50 Stocks": [
        "ACC.NS", "APLAPOLLO.NS", "AUBANK.NS", "ABCAPITAL.NS", "ALKEM.NS",
        "ASHOKLEY.NS", "ASTRAL.NS", "AUROPHARMA.NS", "BHARATFORG.NS", "CGPOWER.NS",
        "COLPAL.NS", "CONCOR.NS", "CUMMINSIND.NS", "DIXON.NS", "FEDERALBNK.NS",
        "GMRAIRPORT.NS", "GODREJPROP.NS", "HDFCAMC.NS", "HINDPETRO.NS", "IDFCFIRSTB.NS",
        "INDHOTEL.NS", "INDUSTOWER.NS", "KPITTECH.NS", "LTF.NS", "LUPIN.NS", "MRF.NS",
        "MARICO.NS", "MAXHEALTH.NS", "MPHASIS.NS", "MUTHOOTFIN.NS", "NMDC.NS",
        "OBEROIRLTY.NS", "OFSS.NS", "POLICYBZR.NS", "PIIND.NS", "PERSISTENT.NS",
        "PETRONET.NS", "PHOENIXLTD.NS", "POLYCAB.NS", "SBICARD.NS", "SRF.NS", "SAIL.NS",
        "SUNDARMFIN.NS", "SUPREMEIND.NS", "SUZLON.NS", "TATACOMM.NS", "UPL.NS", "IDEA.NS",
        "VOLTAS.NS", "YESBANK.NS"
    ],

    "Nifty Smallcap 50 Stocks": [
        "360ONE.NS", "AARTIIND.NS", "ABREL.NS", "ARE&M.NS", "ANGELONE.NS", "APARINDS.NS", "ATUL.NS",
        "BSOFT.NS", "BLUESTARCO.NS", "BRIGADE.NS", "CESC.NS", "CASTROLIND.NS", "CDSL.NS", "CAMS.NS",
        "CROMPTON.NS", "CYIENT.NS", "FINCABLES.NS", "GLENMARK.NS", "GESHIP.NS", "GSPL.NS", "HFCL.NS",
        "HINDCOPPER.NS", "IIFL.NS", "INDIAMART.NS", "IEX.NS", "KPIL.NS", "KARURVYSYA.NS", "LAURUSLABS.NS",
        "MGL.NS", "MANAPPURAM.NS", "MCX.NS", "NATCOPHARM.NS", "NBCC.NS", "NCC.NS", "NH.NS", "NATIONALUM.NS",
        "NAVINFLUOR.NS", "PNBHOUSING.NS", "PVRINOX.NS", "PEL.NS", "PPLPHARMA.NS", "RBLBANK.NS", "RADICO.NS",
        "RKFORGE.NS", "REDINGTON.NS", "SONATSOFTW.NS", "TEJASNET.NS", "RAMCOCEM.NS", "ZEEL.NS", "ZENSARTECH.NS"
    ],
    "Nifty Auto Stocks": [
        "APOLLOTYRE.NS", "ASHOKLEY.NS", "BAJAJ-AUTO.NS", "BALKRISIND.NS", "BHARATFORG.NS",
        "BOSCHLTD.NS", "EICHERMOT.NS", "EXIDEIND.NS", "HEROMOTOCO.NS", "MRF.NS",
        "M&M.NS", "MARUTI.NS", "MOTHERSON.NS", "TVSMOTOR.NS", "TATAMOTORS.NS"
    ],
    "Nifty Bank Stocks": [
        "AUBANK.NS", "AXISBANK.NS", "BANKBARODA.NS", "CANBK.NS", "FEDERALBNK.NS",
        "HDFCBANK.NS", "ICICIBANK.NS", "IDFCFIRSTB.NS", "INDUSINDBK.NS", "KOTAKBANK.NS",
        "PNB.NS", "SBIN.NS"
    ],
    "Nifty Chemicals": [
    "AARTIIND.NS", "ATUL.NS", "BAYERCROP.NS", "CHAMBLFERT.NS", "COROMANDEL.NS", "DEEPAKNTR.NS", "EIDPARRY.NS",
    "FLUOROCHEM.NS", "GNFC.NS", "HSCL.NS", "LINDEINDIA.NS", "NAVINFLUOR.NS", "PCBL.NS", "PIIND.NS", "PIDILITIND.NS",
    "SRF.NS", "SOLARINDS.NS", "SUMICHEM.NS", "TATACHEM.NS", "UPL.NS"
    ],
    "Nifty Financial Services":[
        "AXISBANK.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "CHOLAFIN.NS", "HDFCAMC.NS", "HDFCBANK.NS",
        "HDFCLIFE.NS", "ICICIBANK.NS", "ICICIGI.NS", "ICICIPRULI.NS", "KOTAKBANK.NS", "LICHSGFIN.NS",
        "MCX.NS", "MUTHOOTFIN.NS", "PFC.NS", "RECLTD.NS", "SBICARD.NS", "SBILIFE.NS", "SHRIRAMFIN.NS", "SBIN.NS"
    ],
    "Nifty FMCG":[
        "BALRAMCHIN.NS", "BRITANNIA.NS", "COLPAL.NS", "DABUR.NS", "GODREJCP.NS", "HINDUNILVR.NS",
        "ITC.NS", "MARICO.NS", "NESTLEIND.NS", "PGHH.NS", "RADICO.NS", "TATACONSUM.NS",
        "UBL.NS", "UNITDSPR.NS", "VBL.NS"
    ],
    "Nifty Healthcare":[
        "ABBOTINDIA.NS", "ALKEM.NS", "APOLLOHOSP.NS", "AUROPHARMA.NS", "BIOCON.NS", "CIPLA.NS",
        "DIVISLAB.NS", "LALPATHLAB.NS", "DRREDDY.NS", "GLENMARK.NS", "GRANULES.NS", "IPCALAB.NS",
        "LAURUSLABS.NS", "LUPIN.NS", "MAXHEALTH.NS", "METROPOLIS.NS", "SUNPHARMA.NS", "SYNGENE.NS",
        "TORNTPHARM.NS", "ZYDUSLIFE.NS"
    ],
    "Nifty IT":[
        "COFORGE.NS", "HCLTECH.NS", "INFY.NS", "LTTS.NS", "LTIM.NS", "MPHASIS.NS",
        "PERSISTENT.NS", "TCS.NS", "TECHM.NS", "WIPRO.NS"
    ],
    "Nifty Media":[
        "DEN.NS", "DISHTV.NS", "HATHWAY.NS", "NAZARA.NS", "NETWORK18.NS", "PVRINOX.NS",
        "SAREGAMA.NS", "SUNTV.NS", "TIPSMUSIC.NS", "ZEEL.NS"
    ],
    "Nifty Metal":[
        "APLAPOLLO.NS", "ADANIENT.NS", "HINDALCO.NS", "HINDCOPPER.NS", "HINDZINC.NS", "JSWSTEEL.NS",
        "JSL.NS", "JINDALSTEL.NS", "NMDC.NS", "NATIONALUM.NS", "RATNAMANI.NS", "SAIL.NS",
        "TATASTEEL.NS", "VEDL.NS", "WELCORP.NS"
    ],
    "Nifty Pharma":[
        "ABBOTINDIA.NS", "AJANTPHARM.NS", "ALKEM.NS", "AUROPHARMA.NS", "BIOCON.NS", "CIPLA.NS",
        "DIVISLAB.NS", "DRREDDY.NS", "GLAND.NS", "GLENMARK.NS", "GRANULES.NS", "IPCALAB.NS",
        "JBCHEPHARM.NS", "LAURUSLABS.NS", "LUPIN.NS", "MANKIND.NS", "NATCOPHARM.NS", "SUNPHARMA.NS",
        "TORNTPHARM.NS", "ZYDUSLIFE.NS"
    ],
    "Nifty Private Bank":[
        "AXISBANK.NS", "BANDHANBNK.NS", "CUB.NS", "FEDERALBNK.NS", "HDFCBANK.NS", "ICICIBANK.NS",
        "IDFCFIRSTB.NS", "INDUSINDBK.NS", "KOTAKBANK.NS", "RBLBANK.NS"
    ],
    "Nifty PSU Bank":[
        "BANKBARODA.NS", "BANKINDIA.NS", "MAHABANK.NS", "CANBK.NS", "CENTRALBK.NS", "INDIANB.NS",
        "IOB.NS", "PSB.NS", "PNB.NS", "SBIN.NS", "UCOBANK.NS", "UNIONBANK.NS"
    ],
    "Nifty Realty":[
        "BRIGADE.NS", "DLF.NS", "GODREJPROP.NS", "LODHA.NS", "MAHLIFE.NS", "OBEROIRLTY.NS",
        "PHOENIXLTD.NS", "PRESTIGE.NS", "RAYMOND.NS", "SOBHA.NS"
    ],
    "Nifty Consumer Durables":[
        "AMBER.NS", "BATAINDIA.NS", "BLUESTARCO.NS", "CENTURYPLY.NS", "CERA.NS", "CROMPTON.NS",
        "DIXON.NS", "HAVELLS.NS", "KAJARIACER.NS", "KALYANKJIL.NS", "RAJESHEXPO.NS", "TITAN.NS",
        "VGUARD.NS", "VOLTAS.NS", "WHIRLPOOL.NS"
    ],
    "Nifty Oil & Gas":[
        "ATGL.NS", "AEGISLOG.NS", "BPCL.NS", "CASTROLIND.NS", "GAIL.NS", "GUJGASLTD.NS",
        "GSPL.NS", "HINDPETRO.NS", "IOC.NS", "IGL.NS", "MGL.NS", "ONGC.NS", "OIL.NS",
        "PETRONET.NS", "RELIANCE.NS"
    ],
    "Nifty Commodities":[
        "ACC.NS", "APLAPOLLO.NS", "ADANIENSOL.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "AMBUJACEM.NS",
        "BPCL.NS", "COALINDIA.NS", "GRASIM.NS", "HINDALCO.NS", "HINDPETRO.NS", "IOC.NS",
        "JSWENERGY.NS", "JSWSTEEL.NS", "JINDALSTEL.NS", "NHPC.NS", "NMDC.NS", "NTPC.NS",
        "ONGC.NS", "PIIND.NS", "PIDILITIND.NS", "RELIANCE.NS", "SRF.NS", "SHREECEM.NS",
        "SAIL.NS", "TATAPOWER.NS", "TATASTEEL.NS", "UPL.NS", "ULTRACEMCO.NS", "VEDL.NS"
    ],
    "Nifty Core Housing":[
        "ACC.NS", "AAVAS.NS", "AMBUJACEM.NS", "ASIANPAINT.NS", "BERGEPAINT.NS", "BLUESTARCO.NS",
        "CROMPTON.NS", "DLF.NS", "DALBHARAT.NS", "DIXON.NS", "GODREJPROP.NS", "GRASIM.NS",
        "HAVELLS.NS", "HDFC.NS", "IBULHSGFIN.NS", "JKCEMENT.NS", "KEI.NS", "KAJARIACER.NS",
        "KANSAINER.NS", "LICHSGFIN.NS", "LODHA.NS", "OBEROIRLTY.NS", "PHOENIXLTD.NS", "POLYCAB.NS",
        "PRESTIGE.NS", "SHREECEM.NS", "RAMCOCEM.NS", "ULTRACEMCO.NS", "VOLTAS.NS", "WHIRLPOOL.NS"
    ],
    "Nifty Energy":[
        "ABB.NS", "ADANIENSOL.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "ATGL.NS", "AEGISLOG.NS",
        "BHEL.NS", "BPCL.NS", "CESC.NS", "CGPOWER.NS", "CASTROLIND.NS", "COALINDIA.NS", "GAIL.NS",
        "GVT&D.NS", "GUJGASLTD.NS", "GSPL.NS", "HINDPETRO.NS", "POWERINDIA.NS", "IOC.NS", "IGL.NS",
        "INOXWIND.NS", "JSWENERGY.NS", "JPPOWER.NS", "MGL.NS", "NHPC.NS", "NLCINDIA.NS", "NTPC.NS",
        "ONGC.NS", "OIL.NS", "PETRONET.NS", "POWERGRID.NS", "RELIANCE.NS", "SJVN.NS", "SCHNEIDER.NS",
        "SIEMENS.NS", "SUZLON.NS", "TATAPOWER.NS", "THERMAX.NS", "TORNTPOWER.NS", "TRITURBINE.NS"
    ],
    "Nifty EV & New Age Automotive":[
        "ARE&M.NS", "ASHOKLEY.NS", "BAJAJ-AUTO.NS", "BHARATFORG.NS", "BOSCHLTD.NS", "CGPOWER.NS",
        "EICHERMOT.NS", "EXIDEIND.NS", "FLUOROCHEM.NS", "HEROMOTOCO.NS", "HSCL.NS", "JBMA.NS",
        "JWL.NS", "KPITTECH.NS", "LTTS.NS", "M&M.NS", "MARUTI.NS", "MINDACORP.NS", "MSUMI.NS",
        "OLECTRA.NS", "RTNINDIA.NS", "RELIANCE.NS", "MOTHERSON.NS", "SCHAEFFLER.NS", "SONACOMS.NS",
        "TVSMOTOR.NS", "TATACHEM.NS", "TATAELXSI.NS", "TATAMOTORS.NS", "TATATECH.NS", "TIINDIA.NS",
        "UNOMINDA.NS", "VARROC.NS"
    ],
    "Nifty India Consumption":[
        "ADANIPOWER.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "DMART.NS", "BAJAJ-AUTO.NS", "BHARTIARTL.NS",
        "BRITANNIA.NS", "COLPAL.NS", "DLF.NS", "EICHERMOT.NS", "GODREJCP.NS", "HAVELLS.NS",
        "HEROMOTOCO.NS", "HINDUNILVR.NS", "ITC.NS", "INDHOTEL.NS", "NAUKRI.NS", "INDIGO.NS",
        "M&M.NS", "MARUTI.NS", "MAXHEALTH.NS", "NESTLEIND.NS", "TVSMOTOR.NS", "TATACONSUM.NS",
        "TATAPOWER.NS", "TITAN.NS", "TRENT.NS", "UNITDSPR.NS", "VBL.NS", "ZOMATO.NS"
    ],
    "Nifty India Defence":[
        "ASTRAMICRO.NS", "BDL.NS", "BEL.NS", "COCHINSHIP.NS", "DCXINDIA.NS", "DATAPATTNS.NS",
        "DYNAMATECH.NS", "GRSE.NS", "HAL.NS", "IDEAFORGE.NS", "MTARTECH.NS", "MAZDOCK.NS",
        "MIDHANI.NS", "PARAS.NS", "SOLARINDS.NS", "ZENTEC.NS"
    ],
    "Nifty India Digital":[
        "AFFLE.NS", "BHARTIARTL.NS", "BSOFT.NS", "COFORGE.NS", "CYIENT.NS", "NYKAA.NS",
        "HCLTECH.NS", "INDIAMART.NS", "IRCTC.NS", "NAUKRI.NS", "INFY.NS", "INTELLECT.NS",
        "KPITTECH.NS", "LTTS.NS", "LTIM.NS", "MPHASIS.NS", "PAYTM.NS", "OFSS.NS", "POLICYBZR.NS",
        "PERSISTENT.NS", "SONATSOFTW.NS", "TANLA.NS", "TATACOMM.NS", "TCS.NS", "TATAELXSI.NS",
        "TATATECH.NS", "TECHM.NS", "IDEA.NS", "WIPRO.NS", "ZOMATO.NS"
    ],
    "Nifty India Internet & E-Commerce":[
        "ANGELONE.NS", "FIRSTCRY.NS", "CARTRADE.NS", "EASEMYTRIP.NS", "NYKAA.NS", "IIFLCAPS.NS",
        "INDIAMART.NS", "IRCTC.NS", "INFIBEAM.NS", "NAUKRI.NS", "JUSTDIAL.NS", "IXIGO.NS",
        "MOTILALOFS.NS", "NAZARA.NS", "PAYTM.NS", "POLICYBZR.NS", "RTNINDIA.NS", "SWIGGY.NS",
        "TBOTEK.NS", "THOMASCOOK.NS", "ZOMATO.NS"
    ],
    "Nifty India Manufacturing":[
        "ABB.NS", "AIAENG.NS", "APLAPOLLO.NS", "ABREL.NS", "ASHOKLEY.NS", "ASTRAL.NS", "AUROPHARMA.NS",
        "BAJAJ-AUTO.NS", "BALKRISIND.NS", "BEL.NS", "BHARATFORG.NS", "BHEL.NS", "BPCL.NS", "BOSCHLTD.NS",
        "CGPOWER.NS", "CARBORUNIV.NS", "CASTROLIND.NS", "CIPLA.NS", "COCHINSHIP.NS", "COROMANDEL.NS",
        "CROMPTON.NS", "CUMMINSIND.NS", "DEEPAKNTR.NS", "DIVISLAB.NS", "DIXON.NS", "DRREDDY.NS",
        "EICHERMOT.NS", "ESCORTS.NS", "EXIDEIND.NS", "FLUOROCHEM.NS", "HAVELLS.NS", "HEROMOTOCO.NS",
        "HINDALCO.NS", "HAL.NS", "HINDCOPPER.NS", "HINDZINC.NS", "HONAUT.NS", "IOC.NS", "JSWSTEEL.NS",
        "JINDALSTEL.NS", "KPRMILL.NS", "KEI.NS", "LINDEINDIA.NS", "LLOYDSME.NS", "LUPIN.NS", "MRF.NS",
        "M&M.NS", "MARUTI.NS", "MAZDOCK.NS", "METROBRAND.NS", "PIIND.NS", "PAGEIND.NS", "PIDILITIND.NS",
        "POLYCAB.NS", "RELIANCE.NS", "SKFINDIA.NS", "SRF.NS", "MOTHERSON.NS", "SCHAEFFLER.NS", "SIEMENS.NS",
        "SOLARINDS.NS", "SONACOMS.NS", "SUNPHARMA.NS", "SUPREMEIND.NS", "SUZLON.NS", "TVSMOTOR.NS",
        "TATACHEM.NS", "TATAMOTORS.NS", "TATASTEEL.NS", "TEJASNET.NS", "TIMKEN.NS", "TORNTPHARM.NS",
        "TIINDIA.NS", "UPL.NS", "VEDL.NS", "VOLTAS.NS", "ZYDUSLIFE.NS"
    ],
    "Nifty India New Age Consumption":[
        "360ONE.NS", "ABFRL.NS", "AMBER.NS", "ANANTRAJ.NS", "ANGELONE.NS", "DMART.NS", "BLS.NS",
        "BAJAJ-AUTO.NS", "BATAINDIA.NS", "BHARTIARTL.NS", "BLUESTARCO.NS", "BRIGADE.NS", "CELLO.NS",
        "CHALET.NS", "CROMPTON.NS", "DLF.NS", "DEVYANI.NS", "DIXON.NS", "EIHOTEL.NS", "EICHERMOT.NS",
        "NYKAA.NS", "GODREJPROP.NS", "HDFCAMC.NS", "HAVELLS.NS", "HEROMOTOCO.NS", "ISEC.NS",
        "INDIAMART.NS", "INDHOTEL.NS", "IRCTC.NS", "NAUKRI.NS", "INDIGO.NS", "JUBLFOOD.NS",
        "KPRMILL.NS", "KALYANKJIL.NS", "LEMONTREE.NS", "LODHA.NS", "M&M.NS", "MAHLIFE.NS", "MARUTI.NS",
        "METROBRAND.NS", "MOTILALOFS.NS", "NAM-INDIA.NS", "OBEROIRLTY.NS", "OLECTRA.NS", "PAYTM.NS",
        "POLICYBZR.NS", "PVRINOX.NS", "PAGEIND.NS", "PHOENIXLTD.NS", "PRESTIGE.NS", "RAJESHEXPO.NS",
        "RAYMOND.NS", "SAPPHIRE.NS", "SAREGAMA.NS", "SOBHA.NS", "SUNTV.NS", "TVSMOTOR.NS",
        "TATACOMM.NS", "TATAMOTORS.NS", "TTML.NS", "TITAN.NS", "TRENT.NS", "TRIDENT.NS", "UTIAMC.NS",
        "VGUARD.NS", "VIPIND.NS", "VTL.NS", "MANYAVAR.NS", "IDEA.NS", "VOLTAS.NS", "WELSPUNLIV.NS",
        "WESTLIFE.NS", "WHIRLPOOL.NS", "ZEEL.NS", "ZOMATO.NS"
    ],
    "Nifty India Railways PSU":[
        "BEML.NS", "BEL.NS", "BHEL.NS", "CONCOR.NS", "HINDPETRO.NS", "IRCON.NS", "IRCTC.NS",
        "IRFC.NS", "NTPC.NS", "ONGC.NS", "RITES.NS", "RVNL.NS", "RAILTEL.NS", "SAIL.NS"
    ],
    "Nifty India Tourism":[
        "BLS.NS", "CHALET.NS", "DEVYANI.NS", "EIHOTEL.NS", "EASEMYTRIP.NS", "GMRINFRA.NS",
        "INDHOTEL.NS", "IRCTC.NS", "INDIGO.NS", "JUBLFOOD.NS", "LEMONTREE.NS", "MHRIL.NS",
        "RBA.NS", "SAFARI.NS", "SAPPHIRE.NS", "VIPIND.NS", "WESTLIFE.NS"
    ],
    "Nifty MNC":[
        "3MINDIA.NS", "ABB.NS", "ABBOTINDIA.NS", "AMBUJACEM.NS", "ASHOKLEY.NS", "BATAINDIA.NS",
        "BOSCHLTD.NS", "BRITANNIA.NS", "CRISIL.NS", "CASTROLIND.NS", "COLPAL.NS", "CUMMINSIND.NS",
        "ESCORTS.NS", "GLAND.NS", "GRINDWELL.NS", "HINDUNILVR.NS", "HONAUT.NS", "JBCHEPHARM.NS",
        "LINDEINDIA.NS", "MARUTI.NS", "NESTLEIND.NS", "OFSS.NS", "PGHH.NS", "SKFINDIA.NS",
        "SCHAEFFLER.NS", "SIEMENS.NS", "TIMKEN.NS", "UBL.NS", "UNITDSPR.NS", "VEDL.NS"
    ],
    "Nifty PSE":[
        "BEL.NS", "BHEL.NS", "BPCL.NS", "COALINDIA.NS", "CONCOR.NS", "GAIL.NS", "HAL.NS",
        "HINDPETRO.NS", "IOC.NS", "IRCTC.NS", "IRFC.NS", "NHPC.NS", "NMDC.NS", "NTPC.NS",
        "ONGC.NS", "OIL.NS", "PFC.NS", "POWERGRID.NS", "RECLTD.NS", "SAIL.NS"
    ],
    "Nifty Rural":[
        "ACC.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "AMBUJACEM.NS", "ASHOKLEY.NS", "ASIANPAINT.NS",
        "ASTRAL.NS", "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BANDHANBNK.NS", "BANKBARODA.NS", "BANKINDIA.NS",
        "BERGEPAINT.NS", "BHARTIARTL.NS", "BLUESTARCO.NS", "BRITANNIA.NS", "CHOLAFIN.NS", "COLPAL.NS",
        "COROMANDEL.NS", "CROMPTON.NS", "CUMMINSIND.NS", "DABUR.NS", "DALBHARAT.NS", "DIXON.NS",
        "EICHERMOT.NS", "ELGIEQUIP.NS", "EMAMILTD.NS", "ESCORTS.NS", "GODREJCP.NS", "GRASIM.NS",
        "HDFCLIFE.NS", "HAVELLS.NS", "HEROMOTOCO.NS", "HINDUNILVR.NS", "ICICIPRULI.NS", "ITC.NS",
        "INDIANB.NS", "IRCTC.NS", "JKCEMENT.NS", "JSWENERGY.NS", "JIOFIN.NS", "LICHSGFIN.NS",
        "LICI.NS", "M&MFIN.NS", "M&M.NS", "MARICO.NS", "MARUTI.NS", "MFSL.NS", "MUTHOOTFIN.NS",
        "NHPC.NS", "NTPC.NS", "NESTLEIND.NS", "PIIND.NS", "PATANJALI.NS", "POONAWALLA.NS", "PGHH.NS",
        "PNB.NS", "SBICARD.NS", "SBILIFE.NS", "SHREECEM.NS", "SHRIRAMFIN.NS", "SBIN.NS", "SUNDARMFIN.NS",
        "SUPREMEIND.NS", "TVSMOTOR.NS", "TATACOMM.NS", "TATACONSUM.NS", "TATAMOTORS.NS", "TATAPOWER.NS",
        "TORNTPOWER.NS", "UPL.NS", "ULTRACEMCO.NS", "IDEA.NS", "VOLTAS.NS", "ZEEL.NS"
    ],
    "Nifty Non-Cyclical Consumer":[
        "ASIANPAINT.NS", "DMART.NS", "BHARTIARTL.NS", "BRITANNIA.NS", "COLPAL.NS", "CROMPTON.NS",
        "DABUR.NS", "DIXON.NS", "NYKAA.NS", "GODREJCP.NS", "HAVELLS.NS", "HINDUNILVR.NS", "ITC.NS",
        "INDHOTEL.NS", "IRCTC.NS", "NAUKRI.NS", "INDIGO.NS", "JUBLFOOD.NS", "MARICO.NS", "NESTLEIND.NS",
        "PAGEIND.NS", "TATACOMM.NS", "TATACONSUM.NS", "TITAN.NS", "TRENT.NS", "UNITDSPR.NS", "VBL.NS",
        "VOLTAS.NS", "ZEEL.NS", "ZOMATO.NS"
    ]

}
