# --- Stock Lists ---
STOCK_UNIVERSE = {
    "Nifty 50 Stocks": [
        "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", 
        "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BEL", "BHARTIARTL",
        "CIPLA", "COALINDIA", "DRREDDY", "EICHERMOT", "ETERNAL", 
        "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO",
        "HINDALCO", "HINDUNILVR", "ICICIBANK", "ITC", "INDUSINDBK", 
        "INFY", "JSWSTEEL", "JIOFIN", "KOTAKBANK", "LT",        
        "M&M", "MARUTI", "NTPC", "NESTLEIND", "ONGC", 
        "POWERGRID", "RELIANCE", "SBILIFE", "SHRIRAMFIN", "SBIN",
        "SUNPHARMA", "TCS", "TATACONSUM", "TATAMOTORS", "TATASTEEL", 
        "TECHM", "TITAN", "TRENT", "ULTRACEMCO", "WIPRO"
    ],
    "Nifty Midcap 50 Stocks": [
        "AUBANK", "ALKEM", "ASHOKLEY", "ASTRAL", "AUROPHARMA", 
        "BSE", "BHARATFORG", "BHEL", "COFORGE", "COLPAL",
        "CONCOR", "CUMMINSIND", "DIXON", "FEDERALBNK", "GMRAIRPORT", 
        "GODREJPROP", "HDFCAMC", "HINDPETRO", "IDFCFIRSTB", "IRCTC",    
        "INDUSTOWER", "LUPIN", "MRF", "MARICO", "MAXHEALTH", 
        "MPHASIS", "MUTHOOTFIN", "NHPC", "NMDC", "OBEROIRLTY",    
        "OIL", "PAYTM", "OFSS", "POLICYBZR", "PIIND", 
        "PAGEIND", "PERSISTENT", "PETRONET", "PHOENIXLTD", "POLYCAB",   
        "PRESTIGE", "SBICARD", "SRF", "SAIL", "SUPREMEIND", 
        "TORNTPOWER", "TIINDIA", "IDEA", "VOLTAS", "YESBANK"
    ],

    "Nifty Smallcap 50 Stocks": [
        "AARTIIND", "ABREL", "AEGISLOG", "AFFLE", "ARE&M",
        "AMBER", "ANGELONE", "ASTERDM", "BSOFT", "BRIGADE",  
        "CESC", "CASTROLIND", "CDSL", "CAMS", "CROMPTON",
        "CYIENT", "DELHIVERY", "LALPATHLAB", "FSL", "FIVESTAR",   
        "GESHIP", "GSPL", "HFCL", "HSCL", "HINDCOPPER",
        "IIFL", "IEX", "INOXWIND", "KAYNES", "KEC",   
        "KFINTECH", "LAURUSLABS", "MCX", "NATCOPHARM", "NBCC",
        "NCC", "NAVINFLUOR", "NEULANDLAB", "PNBHOUSING", "PEL",   
        "PPLPHARMA", "POONAWALLA", "RADICO", "RKFORGE", "RPOWER",
        "SONATSOFTW", "TATACHEM", "TEJASNET", "RAMCOCEM", "ZENSARTECH"
    ],
    "Nifty Auto Stocks": [
         "ASHOKLEY", "BAJAJ-AUTO", "BALKRISIND", "BHARATFORG", "BOSCHLTD",
        "EICHERMOT", "EXIDEIND", "HEROMOTOCO", "MRF", "M&M",
        "MARUTI", "MOTHERSON", "TVSMOTOR", "TATAMOTORS", "TIINDIA"
    ],
    "Nifty Bank Stocks": [
        "AUBANK", "AXISBANK", "BANKBARODA", "CANBK", "FEDERALBNK",
        "HDFCBANK", "ICICIBANK", "IDFCFIRSTB", "INDUSINDBK", "KOTAKBANK",
        "PNB", "SBIN"
    ],
    "Nifty Chemicals": [
        "AARTIIND", "ATUL", "BAYERCROP", "CHAMBLFERT", "COROMANDEL",
        "DEEPAKNTR", "EIDPARRY", "FLUOROCHEM", "GNFC", "HSCL",
        "LINDEINDIA", "NAVINFLUOR", "PCBL", "PIIND", "PIDILITIND",
        "SRF", "SOLARINDS", "SUMICHEM", "TATACHEM", "UPL"
    ],
    "Nifty Financial Services":[
        "AXISBANK", "BAJFINANCE", "BAJAJFINSV", "CHOLAFIN", "HDFCAMC",
        "HDFCBANK", "HDFCLIFE", "ICICIBANK", "ICICIGI", "ICICIPRULI",
        "JIOFIN", "KOTAKBANK", "LICHSGFIN", "MUTHOOTFIN", "PFC",
        "RECLTD", "SBICARD", "SBILIFE", "SHRIRAMFIN", "SBIN"
    ],
    "Nifty FMCG":[
        "BRITANNIA", "COLPAL", "DABUR", "EMAMILTD", "GODREJCP",
        "HINDUNILVR", "ITC", "MARICO", "NESTLEIND", "PATANJALI",  
        "RADICO", "TATACONSUM", "UBL", "UNITDSPR", "VBL"
    ],
    "Nifty Healthcare":[
        "ABBOTINDIA", "ALKEM", "APOLLOHOSP", "AUROPHARMA", "BIOCON",
        "CIPLA", "DIVISLAB", "DRREDDY", "FORTIS", "GLENMARK",
        "GRANULES", "IPCALAB", "LAURUSLABS", "LUPIN", "MANKIND",
        "MAXHEALTH", "SUNPHARMA", "SYNGENE", "TORNTPHARM", "ZYDUSLIFE"
    ],
    "Nifty IT":[
        "COFORGE", "HCLTECH", "INFY", "LTIM", "MPHASIS",
        "OFSS", "PERSISTENT", "TCS", "TECHM", "WIPRO"
    ],
    "Nifty Media":[
        "DBCORP", "DISHTV", "HATHWAY", "NAZARA", "NETWORK18",
        "PVRINOX", "SAREGAMA", "SUNTV", "TIPSMUSIC", "ZEEL"
    ],
    "Nifty Metal":[
        "APLAPOLLO", "ADANIENT", "HINDALCO", "HINDCOPPER", "HINDZINC",
        "JSWSTEEL", "JSL", "JINDALSTEL", "LLOYDSME", "NMDC",  
        "NATIONALUM", "SAIL", "TATASTEEL", "VEDL", "WELCORP"
    ],
    "Nifty Pharma":[
        "ABBOTINDIA", "AJANTPHARM", "ALKEM", "AUROPHARMA", "BIOCON",
        "CIPLA", "DIVISLAB", "DRREDDY", "GLAND", "GLENMARK",
        "GRANULES", "IPCALAB", "JBCHEPHARM", "LAURUSLABS", "LUPIN",
        "MANKIND", "NATCOPHARM", "SUNPHARMA", "TORNTPHARM", "ZYDUSLIFE"
    ],
    "Nifty Private Bank":[
        "AXISBANK", "BANDHANBNK", "FEDERALBNK", "HDFCBANK", "ICICIBANK",
        "IDFCFIRSTB", "INDUSINDBK", "KOTAKBANK", "RBLBANK", "YESBANK"
    ],
    "Nifty PSU Bank":[
        "BANKBARODA", "BANKINDIA", "MAHABANK", "CANBK", "CENTRALBK",
        "INDIANB", "IOB", "PSB", "PNB", "SBIN",
        "UCOBANK", "UNIONBANK"
    ],
    "Nifty Realty":[
        "ANANTRAJ", "BRIGADE", "DLF", "DUMMYRAYMN", "GODREJPROP",
        "LODHA", "OBEROIRLTY", "PHOENIXLTD", "PRESTIGE", "RAYMOND",
        "SOBHA"
    ],
    "Nifty Consumer Durables":[
        "AMBER", "BATAINDIA", "BLUESTARCO", "CENTURYPLY", "CERA",
        "CROMPTON", "DIXON", "HAVELLS", "KAJARIACER", "KALYANKJIL",
        "PGEL", "TITAN", "VGUARD", "VOLTAS", "WHIRLPOOL"
    ],
    "Nifty Oil & Gas":[
        "ATGL", "AEGISLOG", "BPCL", "CASTROLIND", "GAIL",
        "GUJGASLTD", "GSPL", "HINDPETRO", "IOC", "IGL",   
        "MGL", "ONGC", "OIL", "PETRONET", "RELIANCE"
    ],
    "Nifty Commodities":[
        "APLAPOLLO", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM",
        "BPCL", "COALINDIA", "GRASIM", "HINDALCO", "HINDPETRO",   
        "IOC", "JSWENERGY", "JSWSTEEL", "JINDALSTEL", "NHPC",
        "NMDC", "NTPC", "ONGC", "OIL", "PIIND",
        "PIDILITIND", "RELIANCE", "SRF", "SHREECEM", "TATAPOWER",
        "TATASTEEL", "TORNTPOWER", "UPL", "ULTRACEMCO", "VEDL"
    ],
    "Nifty Core Housing":[
        "ACC", "AAVAS", "AMBUJACEM", "ASIANPAINT", "BERGEPAINT",
        "BLUESTARCO", "CROMPTON", "DLF", "DALBHARAT", "DIXON",
        "GODREJPROP", "GRASIM", "HAVELLS", "HDFC", "IBULHSGFIN",
        "JKCEMENT", "KEI", "KAJARIACER", "KANSAINER", "LICHSGFIN",
        "LODHA", "OBEROIRLTY", "PHOENIXLTD", "POLYCAB", "PRESTIGE",
        "SHREECEM", "RAMCOCEM", "ULTRACEMCO", "VOLTAS", "WHIRLPOOL"
    ],
    "Nifty Energy":[
        "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "ATGL",
        "AEGISLOG", "BHEL", "BPCL", "CESC", "CGPOWER",
        "CASTROLIND", "COALINDIA", "DUMMYSIEMS", "GAIL", "GVT&D",
        "GUJGASLTD", "GSPL", "HINDPETRO", "POWERINDIA", "IOC",
        "IGL", "INOXWIND", "JSWENERGY", "JPPOWER", "MGL",
        "NHPC", "NLCINDIA", "NTPC", "ONGC", "OIL",
        "PETRONET", "POWERGRID", "RELIANCE", "RPOWER", "SJVN",
        "SIEMENS", "SUZLON", "TATAPOWER", "THERMAX", "TORNTPOWER",
        "TRITURBINE"
    ],
    "Nifty EV & New Age Automotive":[
        "ARE&M", "ASHOKLEY", "BAJAJ-AUTO", "BHARATFORG", "BOSCHLTD",
        "CGPOWER", "EICHERMOT", "EXIDEIND", "FLUOROCHEM", "HEROMOTOCO",
        "HSCL", "JBMA", "JWL", "KPITTECH", "LTTS",
        "M&M", "MARUTI", "MINDACORP", "MSUMI", "OLECTRA",
        "RTNINDIA", "RELIANCE", "MOTHERSON", "SCHAEFFLER", "SONACOMS",
        "TVSMOTOR", "TATACHEM", "TATAELXSI", "TATAMOTORS", "TATATECH",
        "TIINDIA", "UNOMINDA", "VARROC"
    ],
    "Nifty India Consumption":[
        "ADANIPOWER", "APOLLOHOSP", "ASIANPAINT", "DMART", "BAJAJ-AUTO",
        "BHARTIARTL", "BRITANNIA", "COLPAL", "DLF", "EICHERMOT",
        "ETERNAL", "GODREJCP", "HAVELLS", "HEROMOTOCO", "HINDUNILVR",
        "ITC", "INDHOTEL", "NAUKRI", "INDIGO", "M&M",
        "MARUTI", "MAXHEALTH", "NESTLEIND", "TVSMOTOR", "TATACONSUM",
        "TATAPOWER", "TITAN", "TRENT", "UNITDSPR", "VBL"
    ],
    "Nifty India Defence":[
        "ASTRAMICRO", "BEML", "BDL", "BEL", "COCHINSHIP",
        "CYIENTDLM", "DCXINDIA", "DATAPATTNS", "DYNAMATECH", "GRSE",
        "HAL", "MTARTECH", "MAZDOCK", "MIDHANI", "PARAS",
        "SOLARINDS", "UNIMECH", "ZENTEC"
    ],
    "Nifty India Digital":[
        "AFFLE", "BHARTIARTL", "BSOFT", "COFORGE", "CYIENT",
        "ETERNAL", "NYKAA", "HCLTECH", "INDIAMART", "IRCTC",
        "NAUKRI", "INFY", "INTELLECT", "KPITTECH", "LTTS",
        "LTIM", "MPHASIS", "PAYTM", "OFSS", "POLICYBZR",
        "PERSISTENT", "SONATSOFTW", "SWIGGY", "TATACOMM", "TCS",
        "TATAELXSI", "TATATECH", "TECHM", "IDEA", "WIPRO"
    ],
    "Nifty India Internet & E-Commerce":[
        "ANGELONE", "FIRSTCRY", "CARTRADE", "EASEMYTRIP", "ETERNAL",
        "NYKAA", "IIFLCAPS", "INDIAMART", "IRCTC", "INFIBEAM",
        "NAUKRI", "JUSTDIAL", "IXIGO", "MOTILALOFS", "NAZARA",
        "PAYTM", "POLICYBZR", "RTNINDIA", "SWIGGY", "TBOTEK",
        "THOMASCOOK"
    ],
    "Nifty India Manufacturing":[
        "ABB", "AIAENG", "APLAPOLLO", "ABREL", "ALKEM",
        "ASHOKLEY", "ASTRAL", "AUROPHARMA", "BAJAJ-AUTO", "BALKRISIND",
        "BEL", "BHARATFORG", "BHEL", "BPCL", "BLUESTARCO",
        "BOSCHLTD", "CGPOWER", "CASTROLIND", "CIPLA", "COCHINSHIP",
        "COROMANDEL", "CROMPTON", "CUMMINSIND", "DEEPAKNTR", "DIVISLAB",
        "DIXON", "DRREDDY", "DUMMYSIEMS", "EICHERMOT", "ESCORTS",
        "EXIDEIND", "FLUOROCHEM", "HAVELLS", "HEROMOTOCO", "HSCL",
        "HINDALCO", "HAL", "HINDCOPPER", "HINDZINC", "HONAUT",
        "HYUNDAI", "IOC", "JSWSTEEL", "JINDALSTEL", "KPRMILL",
        "KEI", "KAYNES", "LINDEINDIA", "LUPIN", "MRF",
        "M&M", "MARUTI", "MAZDOCK", "PIIND", "PAGEIND",
        "PIDILITIND", "POLYCAB", "RELIANCE", "SRF", "MOTHERSON",
        "SIEMENS", "SOLARINDS", "SONACOMS", "SUNPHARMA", "SUPREMEIND",
        "SUZLON", "TVSMOTOR", "TATACHEM", "TATAMOTORS", "TATASTEEL",
        "TEJASNET", "TORNTPHARM", "TIINDIA", "UPL", "VEDL",
        "VOLTAS", "ZYDUSLIFE"
    ],
    "Nifty India New Age Consumption":[
        "360ONE", "ABFRL", "ABSLAMC", "AMBER", "ANANTRAJ",
        "ANGELONE", "DMART", "BLS", "BAJAJ-AUTO", "BATAINDIA",
        "BHARTIARTL", "BHARTIHEXA", "BLUESTARCO", "FIRSTCRY", "BRIGADE",
        "CHALET", "CROMPTON", "DLF", "DEVYANI", "DIXON",
        "DUMMYABFRL", "DUMMYRAYMN", "EIHOTEL", "EICHERMOT", "ETERNAL",
        "NYKAA", "GODREJPROP", "HDFCAMC", "HAVELLS", "HEROMOTOCO",
        "HYUNDAI", "INDIAMART", "INDHOTEL", "IRCTC", "NAUKRI",
        "INDIGO", "JUBLFOOD", "KPRMILL", "KALYANKJIL", "LEMONTREE",
        "LODHA", "M&M", "MARUTI", "MOTILALOFS", "NETWORK18",
        "NAM-INDIA", "NUVAMA", "OBEROIRLTY", "OLAELEC", "OLECTRA",
        "PAYTM", "POLICYBZR", "PGEL", "PVRINOX", "PAGEIND",
        "PHOENIXLTD", "PRESTIGE", "RAYMOND", "SAPPHIRE", "SOBHA",
        "SUNTV", "SWIGGY", "TVSMOTOR", "TATACOMM", "TATAMOTORS",
        "TITAN", "TRENT", "UTIAMC", "VGUARD", "MANYAVAR",
        "VMM", "IDEA", "VOLTAS", "WELSPUNLIV", "WESTLIFE",
        "WHIRLPOOL", "ZEEL"
    ],
    "Nifty India Railways PSU":[
        "BEML", "BEL", "BHEL", "CONCOR", "HINDPETRO",
        "IRCON", "ITI", "IRCTC", "IRFC", "MRPL",
        "NTPC", "ONGC", "RITES", "RVNL", "RAILTEL",
        "SAIL"
    ],
    "Nifty India Tourism":[
            "BLS", "CHALET", "DEVYANI", "EIHOTEL", "EASEMYTRIP",
            "GMRINFRA", "INDHOTEL", "IRCTC", "INDIGO", "JUBLFOOD",
            "LEMONTREE", "MHRIL", "RBA", "SAFARI", "SAPPHIRE",
            "VIPIND", "WESTLIFE"
        ],
    "Nifty MNC":[
        "3MINDIA", "ABB", "ABBOTINDIA", "AMBUJACEM", "ASHOKLEY",
        "BOSCHLTD", "BRITANNIA", "CRISIL", "CASTROLIND", "COHANCE",
        "COLPAL", "CUMMINSIND", "DUMMYSIEMS", "ESCORTS", "GLAND",
        "HINDUNILVR", "POWERINDIA", "HONAUT", "HYUNDAI", "JBCHEPHARM",
        "LINDEINDIA", "MARUTI", "NESTLEIND", "OFSS", "SKFINDIA",
        "SCHAEFFLER", "SIEMENS", "TIMKEN", "UBL", "UNITDSPR",
        "VEDL"
    ],
    "Nifty PSE":[
        "BEL", "BHEL", "BPCL", "COALINDIA", "CONCOR",
        "GAIL", "HAL", "HINDPETRO", "IOC", "IRCTC",
        "IRFC", "NHPC", "NMDC", "NTPC", "ONGC",
        "OIL", "PFC", "POWERGRID", "RECLTD", "RVNL"
    ],
    "Nifty Rural":[
        "ACC", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "ASHOKLEY",
        "ASIANPAINT", "ASTRAL", "BAJAJ-AUTO", "BAJFINANCE", "BANDHANBNK",
        "BANKBARODA", "BANKINDIA", "BERGEPAINT", "BHARTIARTL", "BLUESTARCO",
        "BRITANNIA", "CHOLAFIN", "COLPAL", "COROMANDEL", "CROMPTON",
        "CUMMINSIND", "DABUR", "DALBHARAT", "DIXON", "EICHERMOT",
        "ELGIEQUIP", "EMAMILTD", "ESCORTS", "GODREJCP", "GRASIM",
        "HDFCLIFE", "HAVELLS", "HEROMOTOCO", "HINDUNILVR", "HYUNDAI",
        "ICICIPRULI", "ITC", "INDIANB", "IRCTC", "JKCEMENT",
        "JSWENERGY", "LICHSGFIN", "LICI", "M&MFIN", "M&M",
        "MARICO", "MARUTI", "MFSL", "MUTHOOTFIN", "NHPC",
        "NTPC", "NESTLEIND", "PIIND", "PNBHOUSING", "PATANJALI",
        "POONAWALLA", "PNB", "SBICARD", "SBILIFE", "SHREECEM",
        "SHRIRAMFIN", "SBIN", "SUNDARMFIN", "SUPREMEIND", "TVSMOTOR",
        "TATACOMM", "TATACONSUM", "TATAMOTORS", "TATAPOWER", "TORNTPOWER",
        "UPL", "ULTRACEMCO", "IDEA", "VOLTAS", "ZEEL"
    ],
    "Nifty Non-Cyclical Consumer":[
        "ASIANPAINT", "DMART", "BHARTIARTL", "BRITANNIA", "COLPAL",
        "CROMPTON", "DABUR", "DIXON", "ETERNAL", "NYKAA",
        "GODREJCP", "HAVELLS", "HINDUNILVR", "ITC", "INDHOTEL",
        "IRCTC", "NAUKRI", "INDIGO", "JUBLFOOD", "MARICO",
        "NESTLEIND", "PAGEIND", "TATACOMM", "TATACONSUM", "TITAN",
        "TRENT", "UNITDSPR", "VBL", "IDEA", "VOLTAS"
    ]

}
